name: smart_medix
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_vector_icons: ^0.2.1


  carousel_pro: ^0.0.13
  firebase_auth: ^0.15.1
  cloud_firestore: ^0.12.11
  flutter_bloc: ^2.1.1
  # flutter_dialogflow: ^0.1.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/two.jpg
   - assets/clinic1.jpg
   - assets/lab.jpeg
   - assets/logopharm.PNG
   - assets/pscy.jpg
   - assets/drug1.jpg
   - assets/drug2.jpg
   - assets/drug3.jpg
   - assets/drug4.jpg
   - assets/drug5.jpg
   - assets/drug6.jpg
   - assets/drug7.jpg
   - assets/drug8.jpg
   - assets/cats/eye.png
   - assets/cats/diet.jpeg
   - assets/cats/fungal.jpeg
   - assets/cats/mos.png
   - assets/cats/ulcer.jpeg
   - assets/cats/worm.jpeg
   - assets/cats/cough.jpeg
   - assets/products/pyrantrin.jpeg
   - assets/products/gestid.jpeg
   - assets/products/sebamed.jpeg
   - assets/products/nystatin.jpeg
   - assets/products/gaviscon.jpeg
   - assets/products/amatem.png
   - assets/products/polyfort.jpeg
   - assets/products/spardium.gif
   - assets/products/coflin.png
   - assets/products/alorepair.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
